apiVersion: batch/v1
kind: Job
metadata:
  name: test-read-annotations
spec:
  template:
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: read-gcs-key
      containers:
      - name: run-test
        image: test-read-annotations
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: BRANCH
          value: testing-dask
      restartPolicy: Never
